// Voxel dimensions for a volume, keyed by its public URL in the manifest.
export interface VolumeDimensions {
  width: number;
  height: number;
  depth: number;
}

type VolumeManifest = Record<string, VolumeDimensions>;

// The manifest is generated by preprocessing/convert-volumes.py and served
// alongside the .raw.zst files. Cache the in-flight/settled request so every
// viewer shares a single fetch.
let manifestPromise: Promise<VolumeManifest> | null = null;

function loadManifest(): Promise<VolumeManifest> {
  if (!manifestPromise) {
    manifestPromise = fetch("/volumes/manifest.json")
      .then((response) => {
        if (!response.ok) {
          throw new Error(
            `Failed to load volume manifest (HTTP ${response.status}).`,
          );
        }
        return response.json() as Promise<VolumeManifest>;
      })
      .catch((error) => {
        // Allow a later attempt to retry instead of caching the failure.
        manifestPromise = null;
        throw error;
      });
  }
  return manifestPromise;
}

export async function loadVolumeDimensions(
  url: string,
): Promise<VolumeDimensions> {
  const manifest = await loadManifest();
  const dimensions = manifest[url];
  if (!dimensions) {
    throw new Error(`No dimensions found for volume "${url}".`);
  }
  return dimensions;
}
