import { decompress } from "fzstd";
import { resolvePublicUrl } from "./assets";
import {
  DEFAULT_SPACING,
  orderVariants,
  variantDefaults,
  type Sample,
} from "../data/variants";

// Voxel dimensions for a volume.
export interface VolumeDimensions {
  width: number;
  height: number;
  depth: number;
}

// A single volume as recorded in the manifest. `type` is the source file stem
// (e.g. "raw"), which maps to a global render configuration.
interface ManifestVariant extends VolumeDimensions {
  type: string;
  url: string;
}

interface ManifestSample {
  id: string;
  title: string;
  description: string;
  variants: ManifestVariant[];
}

interface VolumeManifest {
  samples: ManifestSample[];
}

// The manifest is generated by preprocessing/preprocess.py and served
// alongside the .raw.zst files. Cache the in-flight/settled request so every
// viewer shares a single fetch.
let manifestPromise: Promise<VolumeManifest> | null = null;

function loadManifest(): Promise<VolumeManifest> {
  if (!manifestPromise) {
    manifestPromise = fetch(resolvePublicUrl("/volumes/manifest.json"))
      .then((response) => {
        if (!response.ok) {
          throw new Error(
            `Failed to load volume manifest (HTTP ${response.status}).`,
          );
        }
        return response.json() as Promise<VolumeManifest>;
      })
      .catch((error) => {
        // Allow a later attempt to retry instead of caching the failure.
        manifestPromise = null;
        throw error;
      });
  }
  return manifestPromise;
}

// Build the sample list from the manifest, attaching the global render
// defaults for each variant type.
export async function loadSamples(): Promise<Sample[]> {
  const manifest = await loadManifest();
  return manifest.samples.map((sample) => ({
    id: sample.id,
    title: sample.title,
    description: sample.description,
    variants: orderVariants(
      sample.variants.map((variant) => {
        const defaults = variantDefaults(variant.type);
        return {
          id: variant.type,
          label: defaults.label,
          volume: {
            url: variant.url,
            spacing: DEFAULT_SPACING,
            render: defaults.render,
          },
        };
      }),
    ),
  }));
}

export async function loadVolumeDimensions(
  url: string,
): Promise<VolumeDimensions> {
  const manifest = await loadManifest();
  for (const sample of manifest.samples) {
    for (const variant of sample.variants) {
      if (variant.url === url) {
        return {
          width: variant.width,
          height: variant.height,
          depth: variant.depth,
        };
      }
    }
  }
  throw new Error(`No dimensions found for volume "${url}".`);
}

// Decoded voxel data, keyed by public URL. Cached so switching variants (or
// reopening a sample) never re-downloads and re-decompresses a .raw.zst file.
const volumeDataCache = new Map<string, Uint8Array>();

// In-flight volume requests, keyed by public URL. Sharing the promise means a
// variant that is already being prefetched is never fetched twice: a viewer
// that switches to it simply awaits the existing request.
const volumeDataRequests = new Map<string, Promise<Uint8Array>>();

async function fetchVolumeData(
  url: string,
  dimensions: VolumeDimensions,
): Promise<Uint8Array> {
  const response = await fetch(resolvePublicUrl(url));
  if (!response.ok) {
    throw new Error(`Failed to load volume (HTTP ${response.status}).`);
  }
  const buffer = await response.arrayBuffer();
  let decoded: Uint8Array = new Uint8Array(buffer);
  if (url.endsWith(".zst")) {
    decoded = decompress(decoded);
  }

  const expected = dimensions.width * dimensions.height * dimensions.depth;
  if (decoded.length !== expected) {
    throw new Error(
      `Unexpected volume size: got ${decoded.length} bytes, expected ${expected}.`,
    );
  }

  volumeDataCache.set(url, decoded);
  return decoded;
}

// Load (and cache) the decoded voxel data for a volume. Concurrent callers for
// the same url share a single request, so a variant that is already downloading
// is awaited rather than fetched again.
export function loadVolumeData(
  url: string,
  dimensions: VolumeDimensions,
): Promise<Uint8Array> {
  const cached = volumeDataCache.get(url);
  if (cached) return Promise.resolve(cached);

  const inFlight = volumeDataRequests.get(url);
  if (inFlight) return inFlight;

  const request = fetchVolumeData(url, dimensions).finally(() => {
    volumeDataRequests.delete(url);
  });
  volumeDataRequests.set(url, request);
  return request;
}

// Start loading a volume in the background without awaiting it. Errors are
// swallowed here; a viewer that later needs the volume will surface them.
export function prefetchVolumeData(
  url: string,
  dimensions: VolumeDimensions,
): void {
  void loadVolumeData(url, dimensions).catch(() => {});
}
